# Generated by Django 4.1.1 on 2022-11-20 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Ten menu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay doi')),
            ],
            options={
                'verbose_name': 'Loại đồ ăn',
                'verbose_name_plural': 'Tât cả các loại đồ ăn',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='game_name')),
                ('about_game', models.TextField(blank=True, verbose_name='about_game')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%y/%m/%d', verbose_name='game image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay doi')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='De tai')),
                ('content', models.TextField(blank=True, max_length=2000, null=True, verbose_name='van ban')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay gi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay doi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Binh luan',
                'verbose_name_plural': 'Tat ca Binh luan',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ten menu')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.IntegerField(verbose_name='Gia')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%y/%m/%d', verbose_name='photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay doi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Hien/Dau')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.category', verbose_name='Loai menu')),
            ],
            options={
                'verbose_name': 'Thực đơn',
                'verbose_name_plural': 'Tất cả thực đơn',
                'ordering': ['-price'],
            },
        ),
    ]
