# Generated by Django 4.1.1 on 2022-11-18 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Ten menu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay doi')),
            ],
            options={
                'verbose_name': 'Loai menu',
                'verbose_name_plural': 'All loai menu',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='game_name')),
                ('about_game', models.TextField(blank=True, verbose_name='about_game')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%y/%m/%d', verbose_name='game image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay doi')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ten menu')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.IntegerField(verbose_name='Gia')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%y/%m/%d', verbose_name='photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay doi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Hien/Dau')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.category', verbose_name='Loai menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'All menu',
                'ordering': ['-price'],
            },
        ),
    ]
