# Generated by Django 4.1.1 on 2022-09-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menu_created_at_alter_menu_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-price'], 'verbose_name': 'Menu', 'verbose_name_plural': 'All menu'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Hien/Dau'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ten menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(verbose_name='Gia'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngay doi'),
        ),
    ]
