# Generated by Django 4.1.1 on 2022-10-04 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_games_alter_category_options_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'ordering': ['name'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Ten menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='restaurant.category', verbose_name='Loai menu'),
            preserve_default=False,
        ),
    ]
